### ISSUE TITLE
When we choose one invoice but select all invoice is on.

### ISSUE THREAD

**Issue by AyeThidarThein** [ASATechnologies/POS-Awesome#23]
1. We click the payment at menu
2. Choose one invoice 
3. but Multiple select is on

**Comment by AyeThidarThein** [comment]
https://github.com/user-attachments/assets/dc7792d0-93f0-4ce7-bfe0-4b9b39ed2ac2

**Comment by defendicon** [comment]
Fixed

**Comment by AyeThidarThein** [comment]
I'm afraid to inform that still occur at new version. Please kindly check for this.

https://github.com/user-attachments/assets/cba54a8a-f8ca-4e0f-801e-9de6f571ec07

**Comment by defendicon** [comment]
Dandax123 hasnt review code yet and not pull my code you can install from following link

https://github.com/defendicon/POS-Awesome-V15

**Comment by dandax123** [comment]
Merged  #8 in to branch `version-15`  thanks @defendicon
